<a href="https://colab.research.google.com/github/moulik13/Calculater-Using-HTML-CSS-JS/blob/Basic-Calculator/Car_Price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Libraries 

In [ ]:
import pandas as pd
import numpy as np

## importing Data

In [ ]:
dataset = pd.read_csv('/car_data.csv')
dataset

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


dataset['owner'].isnull().sum() this .isnull()>sum() will check wheather there is a null value or not in the feature "owner" 
"isna(). sum() this syntax returns the number of NaN values in all columns of a pandas DataFrame in Python" 

In [ ]:
dataset['owner'].isnull().sum()

0

.value_counts() this command counts the value of the given feature 

In [ ]:
dataset['owner'].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [ ]:
dataset['seller_type'].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [ ]:
dataset['seller_type'].isnull().sum()

0

## Encoding The Data 

"y is the selling price and x has the array of features that effects the selling price so we have devided them into x and y"

.iloc is a function returns a view of the selected rows and columns from a Pandas DataFrame.

In [ ]:
x = dataset.iloc[:,[1,3,4,6]].values
x
y = dataset.iloc[:,2].values
y

array([ 60000, 135000, 600000, ..., 110000, 865000, 225000])

owner and seller type are unblanced so we are not using them to pridict selling price 

In [ ]:
dataset

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,2] = lb.fit_transform(x[:,2])
lb1 = LabelEncoder()
x[:,3] = lb1.fit_transform(x[:,3])

In [ ]:
x[:,2]

array([4, 4, 1, ..., 4, 1, 4], dtype=object)

In [ ]:
x[:,3]

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

## splitting the data into train test data 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)
print(x_train[:,:])

[[2015 175000 1 1]
 [2012 170000 1 1]
 [2006 110000 4 1]
 ...
 [2016 22000 4 1]
 [2015 70000 1 1]
 [2013 62000 4 1]]


## training the model 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regrassor = RandomForestRegressor(n_estimators=300,random_state=0)
regrassor.fit(x_train, y_train) 

RandomForestRegressor(n_estimators=300, random_state=0)

In [ ]:
accuracy = regrassor.score(x_test,y_test)
print(accuracy*100,'%')

75.79783473129758 %


## performing a test on given input

In [ ]:
new_data = [2017,7000,"Petrol","Manual"]


In [ ]:
new_data[2] = lb.transform([new_data[2]])[0]


ValueError: ignored

In [ ]:
new_data[3] = lb1.transform([new_data[3]])[0]

In [ ]:
print(new_data)
regrassor.predict([new_data])

[2017, 7000, 4, 1]


array([617422.22222222])

### saving the model and encoder using pickle

Pickle is a useful Python tool that allows you to save your ML models, to minimise lengthy re-training and allow you to share, commit, and re-load pre-trained machine learning models. Most data scientists working in ML will use Pickle or Joblib to save their ML model for future use.

In [ ]:
import pickle
pickle.dump(regrassor,open('regressor.pkl','wb'))
pickle.dump(lb,open('lb','wb'))
pickle.dump(lb1,open('lb1','wb'))

model testing on test data is a doubt ?????